version: '3.8'
services:
  app:
    image: api-js-series
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=9000
      - VERSION_API=v1
      - DB_HOST=MyDB
      - DB_USERNAME=root
      - DB_PASSWORD=chepita
      - DB_DATABASE=BD_SERIES
      - DB_DIALECT=mysql
      - DB_PORT=3306
      - JWT_SECRET=API_EWONG
    ports:
      - "9000:9000"