module.exports={
    user:require('./user'),
    busines:require('./busines'),
    event:require('./event'),
    local:require('./local'),
    selling_point:require('./selling_point'),
    serie_for_sell_point:require('./serie_for_sell_point'),
    serie:require('./serie'),
    type:require('./type'),
    type_group:require('./type_group')
}