module.exports={
    user:require('./user'),
    busines:require('./busines'),
    local:require('./local'),
    type:require('./type'),
    type_group:require('./type_group'),
    trade:require('./trade'),
    trade_series:require('./trade_series'),
    license:require('./licences'),
    trade_logs:require('./trade_log'),
    trade_import:require('./trade_import'),
    contact_business:require('./contact_business')
}