const {sequelize} = require('../config/database');
const {DataTypes} = require('sequelize');
const TradeLog = sequelize.define(
    'trade_logs',
    {
        id:{
            primaryKey:true,
            autoIncrement:true,
            allowNull:false,
            type:DataTypes.INTEGER
        },
        business_name:{
            type:DataTypes.STRING,
            allowNull:false
        },
        ruc:{
            type:DataTypes.STRING,
            allowNull:false
        },
        license:{
            type:DataTypes.STRING,
            allowNull:false
        },
        ubication:{
            type:DataTypes.STRING,
            allowNull:false
        },
        trade_business:{
            type:DataTypes.STRING,
            allowNull:false
        },
        address:{
            type:DataTypes.STRING,
            allowNull:false
        },
        duplicate_series:{
            type:DataTypes.BOOLEAN,
            allowNull:true
        },
        sale_organization:{
            type:DataTypes.STRING,
            allowNull:false
        },
        channel:{
            type:DataTypes.STRING,
            allowNull:false
        },
        sector:{
            type:DataTypes.STRING,
            allowNull:false
        },
        debtor:{
            type:DataTypes.STRING,
            allowNull:false
        },
        denomination:{
            type:DataTypes.STRING,
            allowNull:false
        },
        center:{
            type:DataTypes.STRING,
            allowNull:false
        },
        center_charity:{
            type:DataTypes.STRING,
            allowNull:false
        },
        anydesk:{
            type:DataTypes.STRING,
            allowNull:false
        },
        attached_code:{
            type:DataTypes.STRING,
            allowNull:false
        },
        trade_id:{
            type:DataTypes.INTEGER,
            allowNull:false
        },
        electronic_series_fe:{
            type:DataTypes.STRING,
            allowNull:true
        },
        electronic_series_be:{
            type:DataTypes.STRING,
            allowNull:true
        },
        electronic_series_ncf:{
            type:DataTypes.STRING,
            allowNull:true
        },
        electronic_series_ncb:{
            type:DataTypes.STRING,
            allowNull:true
        }
    },
    {
        timestamps:true,
        tableName:'trade_logs'
    }
);

module.exports = TradeLog;